# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: archiver.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'archiver.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61rchiver.proto\x12\x08\x61rchiver\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\xb1\x02\n\rArchiverEvent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x0f\n\x07subject\x18\x04 \x01(\t\x12-\n\ttimestamp\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\"\n\x04\x64\x61ta\x18\x06 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x37\n\x08metadata\x18\x07 \x03(\x0b\x32%.archiver.ArchiverEvent.MetadataEntry\x12\x16\n\x0e\x63orrelation_id\x18\x08 \x01(\t\x12\x10\n\x08trace_id\x18\t \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x91\x01\n\x10\x44ocumentMetadata\x12\x12\n\nindex_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64ocument_id\x18\x02 \x01(\t\x12.\n\nindexed_at\x18\x03 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x12\n\nsize_bytes\x18\x04 \x01(\x03\x12\x10\n\x08\x63hecksum\x18\x05 \x01(\t\"\x83\x01\n\x0e\x41rchiveRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12&\n\x05\x65vent\x18\x02 \x01(\x0b\x32\x17.archiver.ArchiverEvent\x12\x14\n\x0ctarget_index\x18\x03 \x01(\t\x12\x1f\n\x17validate_before_archive\x18\x04 \x01(\x08\"{\n\x0f\x41rchiveResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12,\n\x08metadata\x18\x04 \x01(\x0b\x32\x1a.archiver.DocumentMetadataB,Z*github.com/Nvision-x/archiver-go/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'archiver_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/Nvision-x/archiver-go/api/proto'
  _globals['_ARCHIVEREVENT_METADATAENTRY']._loaded_options = None
  _globals['_ARCHIVEREVENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_ARCHIVEREVENT']._serialized_start=89
  _globals['_ARCHIVEREVENT']._serialized_end=394
  _globals['_ARCHIVEREVENT_METADATAENTRY']._serialized_start=347
  _globals['_ARCHIVEREVENT_METADATAENTRY']._serialized_end=394
  _globals['_DOCUMENTMETADATA']._serialized_start=397
  _globals['_DOCUMENTMETADATA']._serialized_end=542
  _globals['_ARCHIVEREQUEST']._serialized_start=545
  _globals['_ARCHIVEREQUEST']._serialized_end=676
  _globals['_ARCHIVERESPONSE']._serialized_start=678
  _globals['_ARCHIVERESPONSE']._serialized_end=801
# @@protoc_insertion_point(module_scope)
