# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cifs_credentials.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cifs_credentials.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ifs_credentials.proto\x12\x1apipeline.connector.cifs.v1\"\xcc\x02\n\x0f\x43IFSCredentials\x12\x16\n\x0eserver_address\x18\x01 \x01(\t\x12\x12\n\nshare_name\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x0e\n\x06\x64omain\x18\x05 \x01(\t\x12\x13\n\x0bsmb_version\x18\x06 \x01(\t\x12T\n\rmount_options\x18\x07 \x03(\x0b\x32=.pipeline.connector.cifs.v1.CIFSCredentials.MountOptionsEntry\x12\x13\n\x0b\x62ind_folder\x18\x08 \x01(\t\x12\x10\n\x08\x66ull_unc\x18\t \x01(\t\x12\x12\n\nip_address\x18\n \x01(\t\x1a\x33\n\x11MountOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x35Z3github.com/Nvision-x/cifs-connector-be-go/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cifs_credentials_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z3github.com/Nvision-x/cifs-connector-be-go/api/proto'
  _globals['_CIFSCREDENTIALS_MOUNTOPTIONSENTRY']._loaded_options = None
  _globals['_CIFSCREDENTIALS_MOUNTOPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_CIFSCREDENTIALS']._serialized_start=55
  _globals['_CIFSCREDENTIALS']._serialized_end=387
  _globals['_CIFSCREDENTIALS_MOUNTOPTIONSENTRY']._serialized_start=336
  _globals['_CIFSCREDENTIALS_MOUNTOPTIONSENTRY']._serialized_end=387
# @@protoc_insertion_point(module_scope)
