# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import content_transfer_pb2 as content__transfer__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in content_transfer_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ContentTransferServiceStub(object):
    """ContentTransferService streams arbitrary byte content between services.

    The first message of every stream carries an Info metadata message.
    Subsequent messages carry raw bytes. Writer and Reader helpers in this
    package hide the oneof plumbing behind io.Writer / io.Reader. Content
    may originate from a file, an in-memory buffer, a generated string, or
    anything else that can be expressed as bytes.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Upload = channel.stream_unary(
                '/pipeline.content.v1.ContentTransferService/Upload',
                request_serializer=content__transfer__pb2.UploadRequest.SerializeToString,
                response_deserializer=content__transfer__pb2.UploadResponse.FromString,
                _registered_method=True)
        self.Download = channel.unary_stream(
                '/pipeline.content.v1.ContentTransferService/Download',
                request_serializer=content__transfer__pb2.DownloadRequest.SerializeToString,
                response_deserializer=content__transfer__pb2.DownloadResponse.FromString,
                _registered_method=True)


class ContentTransferServiceServicer(object):
    """ContentTransferService streams arbitrary byte content between services.

    The first message of every stream carries an Info metadata message.
    Subsequent messages carry raw bytes. Writer and Reader helpers in this
    package hide the oneof plumbing behind io.Writer / io.Reader. Content
    may originate from a file, an in-memory buffer, a generated string, or
    anything else that can be expressed as bytes.
    """

    def Upload(self, request_iterator, context):
        """Upload streams content from client to server.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Download(self, request, context):
        """Download streams content from server to client.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ContentTransferServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Upload': grpc.stream_unary_rpc_method_handler(
                    servicer.Upload,
                    request_deserializer=content__transfer__pb2.UploadRequest.FromString,
                    response_serializer=content__transfer__pb2.UploadResponse.SerializeToString,
            ),
            'Download': grpc.unary_stream_rpc_method_handler(
                    servicer.Download,
                    request_deserializer=content__transfer__pb2.DownloadRequest.FromString,
                    response_serializer=content__transfer__pb2.DownloadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline.content.v1.ContentTransferService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipeline.content.v1.ContentTransferService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ContentTransferService(object):
    """ContentTransferService streams arbitrary byte content between services.

    The first message of every stream carries an Info metadata message.
    Subsequent messages carry raw bytes. Writer and Reader helpers in this
    package hide the oneof plumbing behind io.Writer / io.Reader. Content
    may originate from a file, an in-memory buffer, a generated string, or
    anything else that can be expressed as bytes.
    """

    @staticmethod
    def Upload(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_unary(
            request_iterator,
            target,
            '/pipeline.content.v1.ContentTransferService/Upload',
            content__transfer__pb2.UploadRequest.SerializeToString,
            content__transfer__pb2.UploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Download(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/pipeline.content.v1.ContentTransferService/Download',
            content__transfer__pb2.DownloadRequest.SerializeToString,
            content__transfer__pb2.DownloadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
