# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: content_transfer.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'content_transfer.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x63ontent_transfer.proto\x12\x13pipeline.content.v1\"S\n\rUploadRequest\x12)\n\x04info\x18\x01 \x01(\x0b\x32\x19.pipeline.content.v1.InfoH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta\";\n\x0eUploadResponse\x12\x0b\n\x03urn\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\x12\x0e\n\x06sha256\x18\x03 \x01(\t\"2\n\x0f\x44ownloadRequest\x12\x0b\n\x03urn\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\"V\n\x10\x44ownloadResponse\x12)\n\x04info\x18\x01 \x01(\x0b\x32\x19.pipeline.content.v1.InfoH\x00\x12\x0f\n\x05\x63hunk\x18\x02 \x01(\x0cH\x00\x42\x06\n\x04\x64\x61ta\"\xb7\x01\n\x04Info\x12\x0b\n\x03urn\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\x03\x12\x14\n\x0c\x63ontent_type\x18\x03 \x01(\t\x12\x39\n\x08metadata\x18\x04 \x03(\x0b\x32\'.pipeline.content.v1.Info.MetadataEntry\x12\x12\n\nrequest_id\x18\x05 \x01(\t\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x32\xc8\x01\n\x16\x43ontentTransferService\x12S\n\x06Upload\x12\".pipeline.content.v1.UploadRequest\x1a#.pipeline.content.v1.UploadResponse(\x01\x12Y\n\x08\x44ownload\x12$.pipeline.content.v1.DownloadRequest\x1a%.pipeline.content.v1.DownloadResponse0\x01\x42\x34Z2github.com/Nvision-x/pipeline-lib-go/proto/fetchpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'content_transfer_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/Nvision-x/pipeline-lib-go/proto/fetchpb'
  _globals['_INFO_METADATAENTRY']._loaded_options = None
  _globals['_INFO_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_UPLOADREQUEST']._serialized_start=47
  _globals['_UPLOADREQUEST']._serialized_end=130
  _globals['_UPLOADRESPONSE']._serialized_start=132
  _globals['_UPLOADRESPONSE']._serialized_end=191
  _globals['_DOWNLOADREQUEST']._serialized_start=193
  _globals['_DOWNLOADREQUEST']._serialized_end=243
  _globals['_DOWNLOADRESPONSE']._serialized_start=245
  _globals['_DOWNLOADRESPONSE']._serialized_end=331
  _globals['_INFO']._serialized_start=334
  _globals['_INFO']._serialized_end=517
  _globals['_INFO_METADATAENTRY']._serialized_start=470
  _globals['_INFO_METADATAENTRY']._serialized_end=517
  _globals['_CONTENTTRANSFERSERVICE']._serialized_start=520
  _globals['_CONTENTTRANSFERSERVICE']._serialized_end=720
# @@protoc_insertion_point(module_scope)
