# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: credential_requests.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'credential_requests.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19\x63redential_requests.proto\x12\x1dpipeline.credentialmanager.v1\x1a\x19google/protobuf/any.proto\"T\n\x1dGetConnectorCredentialRequest\x12\x15\n\rdatasource_id\x18\x01 \x01(\t\x12\x1c\n\x14\x64\x61tasource_access_id\x18\x02 \x01(\t\"b\n\x1eGetConnectorCredentialResponse\x12\x15\n\rdatasource_id\x18\x01 \x01(\t\x12)\n\x0b\x63redentials\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\"\x82\x01\n CreateConnectorCredentialRequest\x12\x15\n\rdatasource_id\x18\x01 \x01(\t\x12)\n\x0b\x63redentials\x18\x02 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x1c\n\x14\x64\x61tasource_access_id\x18\x03 \x01(\t\"\\\n!CreateConnectorCredentialResponse\x12\x15\n\rdatasource_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x0f\n\x07message\x18\x03 \x01(\t2\xcc\x02\n\x11\x43redentialService\x12\x95\x01\n\x16GetConnectorCredential\x12<.pipeline.credentialmanager.v1.GetConnectorCredentialRequest\x1a=.pipeline.credentialmanager.v1.GetConnectorCredentialResponse\x12\x9e\x01\n\x19\x43reateConnectorCredential\x12?.pipeline.credentialmanager.v1.CreateConnectorCredentialRequest\x1a@.pipeline.credentialmanager.v1.CreateConnectorCredentialResponseB8Z6github.com/Nvision-x/credentialmanager-be-go/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'credential_requests_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z6github.com/Nvision-x/credentialmanager-be-go/api/proto'
  _globals['_GETCONNECTORCREDENTIALREQUEST']._serialized_start=87
  _globals['_GETCONNECTORCREDENTIALREQUEST']._serialized_end=171
  _globals['_GETCONNECTORCREDENTIALRESPONSE']._serialized_start=173
  _globals['_GETCONNECTORCREDENTIALRESPONSE']._serialized_end=271
  _globals['_CREATECONNECTORCREDENTIALREQUEST']._serialized_start=274
  _globals['_CREATECONNECTORCREDENTIALREQUEST']._serialized_end=404
  _globals['_CREATECONNECTORCREDENTIALRESPONSE']._serialized_start=406
  _globals['_CREATECONNECTORCREDENTIALRESPONSE']._serialized_end=498
  _globals['_CREDENTIALSERVICE']._serialized_start=501
  _globals['_CREDENTIALSERVICE']._serialized_end=833
# @@protoc_insertion_point(module_scope)
