# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import credential_requests_pb2 as credential__requests__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in credential_requests_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CredentialServiceStub(object):
    """CredentialService provides access to connector credentials
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetConnectorCredential = channel.unary_unary(
                '/pipeline.credentialmanager.v1.CredentialService/GetConnectorCredential',
                request_serializer=credential__requests__pb2.GetConnectorCredentialRequest.SerializeToString,
                response_deserializer=credential__requests__pb2.GetConnectorCredentialResponse.FromString,
                _registered_method=True)
        self.CreateConnectorCredential = channel.unary_unary(
                '/pipeline.credentialmanager.v1.CredentialService/CreateConnectorCredential',
                request_serializer=credential__requests__pb2.CreateConnectorCredentialRequest.SerializeToString,
                response_deserializer=credential__requests__pb2.CreateConnectorCredentialResponse.FromString,
                _registered_method=True)


class CredentialServiceServicer(object):
    """CredentialService provides access to connector credentials
    """

    def GetConnectorCredential(self, request, context):
        """GetConnectorCredential retrieves credentials for a specific connector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateConnectorCredential(self, request, context):
        """CreateConnectorCredential creates or updates credentials for a connector
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CredentialServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetConnectorCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.GetConnectorCredential,
                    request_deserializer=credential__requests__pb2.GetConnectorCredentialRequest.FromString,
                    response_serializer=credential__requests__pb2.GetConnectorCredentialResponse.SerializeToString,
            ),
            'CreateConnectorCredential': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateConnectorCredential,
                    request_deserializer=credential__requests__pb2.CreateConnectorCredentialRequest.FromString,
                    response_serializer=credential__requests__pb2.CreateConnectorCredentialResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'pipeline.credentialmanager.v1.CredentialService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('pipeline.credentialmanager.v1.CredentialService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CredentialService(object):
    """CredentialService provides access to connector credentials
    """

    @staticmethod
    def GetConnectorCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline.credentialmanager.v1.CredentialService/GetConnectorCredential',
            credential__requests__pb2.GetConnectorCredentialRequest.SerializeToString,
            credential__requests__pb2.GetConnectorCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateConnectorCredential(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/pipeline.credentialmanager.v1.CredentialService/CreateConnectorCredential',
            credential__requests__pb2.CreateConnectorCredentialRequest.SerializeToString,
            credential__requests__pb2.CreateConnectorCredentialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
