# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: database.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61tabase.proto\x12\x16pipeline.utils.scan.v1\"u\n\x0c\x44\x61tabaseFork\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x0e\n\x06schema\x18\x02 \x01(\t\x12\x15\n\rdatasource_id\x18\x03 \x01(\t\x12\x1c\n\x14\x64\x61tasource_access_id\x18\x04 \x01(\t\x12\x0e\n\x06job_id\x18\x05 \x01(\t\"b\n\x11MaskingPolicyInfo\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x03 \x01(\t\x12\x0e\n\x06schema\x18\x04 \x01(\t\x12\x0e\n\x06\x61\x63tive\x18\x05 \x01(\x08\"\x8d\x01\n\tColumnTag\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x03 \x01(\t\x12\x0e\n\x06schema\x18\x04 \x01(\t\x12\x41\n\x0emasking_policy\x18\x05 \x01(\x0b\x32).pipeline.utils.scan.v1.MaskingPolicyInfo\"\x87\x01\n\x11\x43olumnInformation\x12\x41\n\x0emasking_policy\x18\x01 \x01(\x0b\x32).pipeline.utils.scan.v1.MaskingPolicyInfo\x12/\n\x04tags\x18\x02 \x03(\x0b\x32!.pipeline.utils.scan.v1.ColumnTag\"\x81\x02\n\x0e\x43olumnMetadata\x12\x0b\n\x03pqn\x18\x01 \x01(\t\x12\x13\n\x0b\x63olumn_name\x18\x02 \x01(\t\x12\x11\n\tdata_type\x18\x03 \x01(\t\x12\x10\n\x08nullable\x18\x04 \x01(\x08\x12\x0e\n\x06masked\x18\x05 \x01(\x08\x12\x1a\n\x12table_or_view_name\x18\x06 \x01(\t\x12\x12\n\ntable_type\x18\x07 \x01(\t\x12\x13\n\x0bschema_name\x18\x08 \x01(\t\x12\x15\n\rdatabase_name\x18\t \x01(\t\x12\x17\n\x0f\x64\x61tabase_server\x18\n \x01(\t\x12\x11\n\trow_count\x18\x0b \x01(\x04\x12\x10\n\x08\x63omments\x18\x0c \x01(\tB,Z*github.com/Nvision-x/pipeline-lib-go/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/Nvision-x/pipeline-lib-go/proto'
  _globals['_DATABASEFORK']._serialized_start=42
  _globals['_DATABASEFORK']._serialized_end=159
  _globals['_MASKINGPOLICYINFO']._serialized_start=161
  _globals['_MASKINGPOLICYINFO']._serialized_end=259
  _globals['_COLUMNTAG']._serialized_start=262
  _globals['_COLUMNTAG']._serialized_end=403
  _globals['_COLUMNINFORMATION']._serialized_start=406
  _globals['_COLUMNINFORMATION']._serialized_end=541
  _globals['_COLUMNMETADATA']._serialized_start=544
  _globals['_COLUMNMETADATA']._serialized_end=801
# @@protoc_insertion_point(module_scope)
