# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x65vents.proto\x12\x17pipeline.utils.event.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x19google/protobuf/any.proto\"\x81\x02\n\x05\x45vent\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04type\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\x12\x0f\n\x07subject\x18\x04 \x01(\t\x12(\n\x04time\x18\x05 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12>\n\x08metadata\x18\x06 \x03(\x0b\x32,.pipeline.utils.event.v1.Event.MetadataEntry\x12\"\n\x04\x64\x61ta\x18\x07 \x01(\x0b\x32\x14.google.protobuf.Any\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"<\n\nEventBatch\x12.\n\x06\x65vents\x18\x01 \x03(\x0b\x32\x1e.pipeline.utils.event.v1.Event\"\xce\x01\n\x0c\x45ventRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0e\n\x06method\x18\x02 \x01(\t\x12%\n\x07payload\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\x12\x43\n\x07headers\x18\x04 \x03(\x0b\x32\x32.pipeline.utils.event.v1.EventRequest.HeadersEntry\x1a.\n\x0cHeadersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"o\n\rEventResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\x15\n\rerror_message\x18\x03 \x01(\t\x12\"\n\x04\x64\x61ta\x18\x04 \x01(\x0b\x32\x14.google.protobuf.AnyB,Z*github.com/Nvision-x/pipeline-lib-go/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/Nvision-x/pipeline-lib-go/proto'
  _globals['_EVENT_METADATAENTRY']._loaded_options = None
  _globals['_EVENT_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_EVENTREQUEST_HEADERSENTRY']._loaded_options = None
  _globals['_EVENTREQUEST_HEADERSENTRY']._serialized_options = b'8\001'
  _globals['_EVENT']._serialized_start=102
  _globals['_EVENT']._serialized_end=359
  _globals['_EVENT_METADATAENTRY']._serialized_start=312
  _globals['_EVENT_METADATAENTRY']._serialized_end=359
  _globals['_EVENTBATCH']._serialized_start=361
  _globals['_EVENTBATCH']._serialized_end=421
  _globals['_EVENTREQUEST']._serialized_start=424
  _globals['_EVENTREQUEST']._serialized_end=630
  _globals['_EVENTREQUEST_HEADERSENTRY']._serialized_start=584
  _globals['_EVENTREQUEST_HEADERSENTRY']._serialized_end=630
  _globals['_EVENTRESPONSE']._serialized_start=632
  _globals['_EVENTRESPONSE']._serialized_end=743
# @@protoc_insertion_point(module_scope)
