# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import jobengine_pb2 as jobengine__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in jobengine_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ControlPlaneServiceStub(object):
    """Control Plane Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreatePipeline = channel.unary_unary(
                '/jobengine.ControlPlaneService/CreatePipeline',
                request_serializer=jobengine__pb2.CreatePipelineRequest.SerializeToString,
                response_deserializer=jobengine__pb2.CreatePipelineResponse.FromString,
                _registered_method=True)
        self.GetPipeline = channel.unary_unary(
                '/jobengine.ControlPlaneService/GetPipeline',
                request_serializer=jobengine__pb2.GetPipelineRequest.SerializeToString,
                response_deserializer=jobengine__pb2.GetPipelineResponse.FromString,
                _registered_method=True)
        self.ListPipelines = channel.unary_unary(
                '/jobengine.ControlPlaneService/ListPipelines',
                request_serializer=jobengine__pb2.ListPipelinesRequest.SerializeToString,
                response_deserializer=jobengine__pb2.ListPipelinesResponse.FromString,
                _registered_method=True)
        self.DeletePipeline = channel.unary_unary(
                '/jobengine.ControlPlaneService/DeletePipeline',
                request_serializer=jobengine__pb2.DeletePipelineRequest.SerializeToString,
                response_deserializer=jobengine__pb2.DeletePipelineResponse.FromString,
                _registered_method=True)
        self.CreateJob = channel.unary_unary(
                '/jobengine.ControlPlaneService/CreateJob',
                request_serializer=jobengine__pb2.CreateJobRequest.SerializeToString,
                response_deserializer=jobengine__pb2.CreateJobResponse.FromString,
                _registered_method=True)
        self.GetJob = channel.unary_unary(
                '/jobengine.ControlPlaneService/GetJob',
                request_serializer=jobengine__pb2.GetJobRequest.SerializeToString,
                response_deserializer=jobengine__pb2.GetJobResponse.FromString,
                _registered_method=True)
        self.ListJobs = channel.unary_unary(
                '/jobengine.ControlPlaneService/ListJobs',
                request_serializer=jobengine__pb2.ListJobsRequest.SerializeToString,
                response_deserializer=jobengine__pb2.ListJobsResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/jobengine.ControlPlaneService/GetJobStatus',
                request_serializer=jobengine__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=jobengine__pb2.GetJobStatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/jobengine.ControlPlaneService/CancelJob',
                request_serializer=jobengine__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=jobengine__pb2.CancelJobResponse.FromString,
                _registered_method=True)
        self.GetJobSettings = channel.unary_unary(
                '/jobengine.ControlPlaneService/GetJobSettings',
                request_serializer=jobengine__pb2.GetJobSettingsRequest.SerializeToString,
                response_deserializer=jobengine__pb2.GetJobSettingsResponse.FromString,
                _registered_method=True)


class ControlPlaneServiceServicer(object):
    """Control Plane Service
    """

    def CreatePipeline(self, request, context):
        """Pipeline management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPipelines(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePipeline(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateJob(self, request, context):
        """Job management
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobSettings(self, request, context):
        """Job settings retrieval for microservices
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ControlPlaneServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreatePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.CreatePipeline,
                    request_deserializer=jobengine__pb2.CreatePipelineRequest.FromString,
                    response_serializer=jobengine__pb2.CreatePipelineResponse.SerializeToString,
            ),
            'GetPipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPipeline,
                    request_deserializer=jobengine__pb2.GetPipelineRequest.FromString,
                    response_serializer=jobengine__pb2.GetPipelineResponse.SerializeToString,
            ),
            'ListPipelines': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPipelines,
                    request_deserializer=jobengine__pb2.ListPipelinesRequest.FromString,
                    response_serializer=jobengine__pb2.ListPipelinesResponse.SerializeToString,
            ),
            'DeletePipeline': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePipeline,
                    request_deserializer=jobengine__pb2.DeletePipelineRequest.FromString,
                    response_serializer=jobengine__pb2.DeletePipelineResponse.SerializeToString,
            ),
            'CreateJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateJob,
                    request_deserializer=jobengine__pb2.CreateJobRequest.FromString,
                    response_serializer=jobengine__pb2.CreateJobResponse.SerializeToString,
            ),
            'GetJob': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJob,
                    request_deserializer=jobengine__pb2.GetJobRequest.FromString,
                    response_serializer=jobengine__pb2.GetJobResponse.SerializeToString,
            ),
            'ListJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ListJobs,
                    request_deserializer=jobengine__pb2.ListJobsRequest.FromString,
                    response_serializer=jobengine__pb2.ListJobsResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=jobengine__pb2.GetJobStatusRequest.FromString,
                    response_serializer=jobengine__pb2.GetJobStatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=jobengine__pb2.CancelJobRequest.FromString,
                    response_serializer=jobengine__pb2.CancelJobResponse.SerializeToString,
            ),
            'GetJobSettings': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobSettings,
                    request_deserializer=jobengine__pb2.GetJobSettingsRequest.FromString,
                    response_serializer=jobengine__pb2.GetJobSettingsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jobengine.ControlPlaneService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jobengine.ControlPlaneService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ControlPlaneService(object):
    """Control Plane Service
    """

    @staticmethod
    def CreatePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.ControlPlaneService/CreatePipeline',
            jobengine__pb2.CreatePipelineRequest.SerializeToString,
            jobengine__pb2.CreatePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.ControlPlaneService/GetPipeline',
            jobengine__pb2.GetPipelineRequest.SerializeToString,
            jobengine__pb2.GetPipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPipelines(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.ControlPlaneService/ListPipelines',
            jobengine__pb2.ListPipelinesRequest.SerializeToString,
            jobengine__pb2.ListPipelinesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePipeline(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.ControlPlaneService/DeletePipeline',
            jobengine__pb2.DeletePipelineRequest.SerializeToString,
            jobengine__pb2.DeletePipelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.ControlPlaneService/CreateJob',
            jobengine__pb2.CreateJobRequest.SerializeToString,
            jobengine__pb2.CreateJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.ControlPlaneService/GetJob',
            jobengine__pb2.GetJobRequest.SerializeToString,
            jobengine__pb2.GetJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.ControlPlaneService/ListJobs',
            jobengine__pb2.ListJobsRequest.SerializeToString,
            jobengine__pb2.ListJobsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.ControlPlaneService/GetJobStatus',
            jobengine__pb2.GetJobStatusRequest.SerializeToString,
            jobengine__pb2.GetJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.ControlPlaneService/CancelJob',
            jobengine__pb2.CancelJobRequest.SerializeToString,
            jobengine__pb2.CancelJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobSettings(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.ControlPlaneService/GetJobSettings',
            jobengine__pb2.GetJobSettingsRequest.SerializeToString,
            jobengine__pb2.GetJobSettingsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ObserverServiceStub(object):
    """Observer Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetBatchProgress = channel.unary_unary(
                '/jobengine.ObserverService/GetBatchProgress',
                request_serializer=jobengine__pb2.GetBatchProgressRequest.SerializeToString,
                response_deserializer=jobengine__pb2.GetBatchProgressResponse.FromString,
                _registered_method=True)
        self.GetMetrics = channel.unary_unary(
                '/jobengine.ObserverService/GetMetrics',
                request_serializer=jobengine__pb2.GetMetricsRequest.SerializeToString,
                response_deserializer=jobengine__pb2.GetMetricsResponse.FromString,
                _registered_method=True)
        self.StreamTelemetry = channel.unary_stream(
                '/jobengine.ObserverService/StreamTelemetry',
                request_serializer=jobengine__pb2.StreamTelemetryRequest.SerializeToString,
                response_deserializer=jobengine__pb2.TelemetryEvent.FromString,
                _registered_method=True)


class ObserverServiceServicer(object):
    """Observer Service
    """

    def GetBatchProgress(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMetrics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamTelemetry(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ObserverServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetBatchProgress': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBatchProgress,
                    request_deserializer=jobengine__pb2.GetBatchProgressRequest.FromString,
                    response_serializer=jobengine__pb2.GetBatchProgressResponse.SerializeToString,
            ),
            'GetMetrics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMetrics,
                    request_deserializer=jobengine__pb2.GetMetricsRequest.FromString,
                    response_serializer=jobengine__pb2.GetMetricsResponse.SerializeToString,
            ),
            'StreamTelemetry': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTelemetry,
                    request_deserializer=jobengine__pb2.StreamTelemetryRequest.FromString,
                    response_serializer=jobengine__pb2.TelemetryEvent.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jobengine.ObserverService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jobengine.ObserverService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ObserverService(object):
    """Observer Service
    """

    @staticmethod
    def GetBatchProgress(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.ObserverService/GetBatchProgress',
            jobengine__pb2.GetBatchProgressRequest.SerializeToString,
            jobengine__pb2.GetBatchProgressResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMetrics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.ObserverService/GetMetrics',
            jobengine__pb2.GetMetricsRequest.SerializeToString,
            jobengine__pb2.GetMetricsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamTelemetry(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jobengine.ObserverService/StreamTelemetry',
            jobengine__pb2.StreamTelemetryRequest.SerializeToString,
            jobengine__pb2.TelemetryEvent.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class HealthServiceStub(object):
    """Health Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Check = channel.unary_unary(
                '/jobengine.HealthService/Check',
                request_serializer=jobengine__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=jobengine__pb2.HealthCheckResponse.FromString,
                _registered_method=True)
        self.Watch = channel.unary_stream(
                '/jobengine.HealthService/Watch',
                request_serializer=jobengine__pb2.HealthCheckRequest.SerializeToString,
                response_deserializer=jobengine__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class HealthServiceServicer(object):
    """Health Service
    """

    def Check(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Watch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HealthServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Check': grpc.unary_unary_rpc_method_handler(
                    servicer.Check,
                    request_deserializer=jobengine__pb2.HealthCheckRequest.FromString,
                    response_serializer=jobengine__pb2.HealthCheckResponse.SerializeToString,
            ),
            'Watch': grpc.unary_stream_rpc_method_handler(
                    servicer.Watch,
                    request_deserializer=jobengine__pb2.HealthCheckRequest.FromString,
                    response_serializer=jobengine__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'jobengine.HealthService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('jobengine.HealthService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HealthService(object):
    """Health Service
    """

    @staticmethod
    def Check(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/jobengine.HealthService/Check',
            jobengine__pb2.HealthCheckRequest.SerializeToString,
            jobengine__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Watch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/jobengine.HealthService/Watch',
            jobengine__pb2.HealthCheckRequest.SerializeToString,
            jobengine__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
