# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nfs_fork.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nfs_fork.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0enfs_fork.proto\x12\x19pipeline.connector.nfs.v1\"}\n\x07NFSFork\x12\x14\n\x0cstart_folder\x18\x01 \x01(\t\x12\x1c\n\x14\x64\x61tasource_access_id\x18\x02 \x01(\t\x12\x0e\n\x06job_id\x18\x03 \x01(\t\x12\x17\n\x0f\x64\x61tasource_name\x18\x04 \x01(\t\x12\x15\n\rdatasource_id\x18\x05 \x01(\tB4Z2github.com/Nvision-x/nfs-connector-be-go/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nfs_fork_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/Nvision-x/nfs-connector-be-go/api/proto'
  _globals['_NFSFORK']._serialized_start=45
  _globals['_NFSFORK']._serialized_end=170
# @@protoc_insertion_point(module_scope)
