# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: nfs_credentials.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'nfs_credentials.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15nfs_credentials.proto\x12\x19pipeline.connector.nfs.v1\"\xfa\x01\n\x0eNFSCredentials\x12\x16\n\x0eserver_address\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\x12\x13\n\x0b\x65xport_path\x18\x03 \x01(\t\x12\x13\n\x0b\x62ind_folder\x18\x04 \x01(\t\x12\x0f\n\x07version\x18\x05 \x01(\t\x12R\n\rmount_options\x18\x06 \x03(\x0b\x32;.pipeline.connector.nfs.v1.NFSCredentials.MountOptionsEntry\x1a\x33\n\x11MountOptionsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x42\x34Z2github.com/Nvision-x/nfs-connector-be-go/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'nfs_credentials_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z2github.com/Nvision-x/nfs-connector-be-go/api/proto'
  _globals['_NFSCREDENTIALS_MOUNTOPTIONSENTRY']._loaded_options = None
  _globals['_NFSCREDENTIALS_MOUNTOPTIONSENTRY']._serialized_options = b'8\001'
  _globals['_NFSCREDENTIALS']._serialized_start=53
  _globals['_NFSCREDENTIALS']._serialized_end=303
  _globals['_NFSCREDENTIALS_MOUNTOPTIONSENTRY']._serialized_start=252
  _globals['_NFSCREDENTIALS_MOUNTOPTIONSENTRY']._serialized_end=303
# @@protoc_insertion_point(module_scope)
