# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: postgresql.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'postgresql.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10postgresql.proto\x12 pipeline.connector.postgresql.v1\"\xec\x01\n\x1bPostgreSQLConnectorSpecific\x12\x17\n\x0f\x63ontent_skipped\x18\x01 \x01(\x08\x12\'\n\x1f\x61\x63\x63\x65ss_detail_fullcontrol_email\x18\x02 \x03(\t\x12!\n\x19\x61\x63\x63\x65ss_detail_write_email\x18\x03 \x03(\t\x12 \n\x18\x61\x63\x63\x65ss_detail_read_email\x18\x04 \x03(\t\x12\x14\n\x0c\x63har_max_len\x18\x05 \x01(\x03\x12\x19\n\x11numeric_precision\x18\x06 \x01(\x03\x12\x15\n\rnumeric_scale\x18\x07 \x01(\x03\"\xca\x01\n\x15PostgreSQLCredentials\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\t\x12\x10\n\x08\x64\x61tabase\x18\x05 \x01(\t\x12\x10\n\x08ssl_mode\x18\x06 \x01(\t\x12\x10\n\x08ssl_cert\x18\x07 \x01(\t\x12\x0f\n\x07ssl_key\x18\x08 \x01(\t\x12\x15\n\rssl_root_cert\x18\t \x01(\t\x12\x13\n\x0bsample_size\x18\x0e \x01(\x05\x42;Z9github.com/Nvision-x/postgresql-connector-be-go/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'postgresql_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/Nvision-x/postgresql-connector-be-go/api/proto'
  _globals['_POSTGRESQLCONNECTORSPECIFIC']._serialized_start=55
  _globals['_POSTGRESQLCONNECTORSPECIFIC']._serialized_end=291
  _globals['_POSTGRESQLCREDENTIALS']._serialized_start=294
  _globals['_POSTGRESQLCREDENTIALS']._serialized_end=496
# @@protoc_insertion_point(module_scope)
