# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: process_events.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'process_events.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14process_events.proto\x12\x19pipeline.utils.process.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xaa\x01\n\x13ProcessStartedEvent\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\nprocess_id\x18\x02 \x01(\t\x12\x19\n\x11parent_process_id\x18\x03 \x01(\t\x12\x0f\n\x07step_id\x18\x04 \x01(\t\x12\x14\n\x0cservice_name\x18\x05 \x01(\t\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x87\x02\n\x15ProcessCompletedEvent\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\nprocess_id\x18\x02 \x01(\t\x12\x19\n\x11parent_process_id\x18\x03 \x01(\t\x12\x0f\n\x07step_id\x18\x04 \x01(\t\x12\x14\n\x0cservice_name\x18\x05 \x01(\t\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x0f\n\x07outcome\x18\x07 \x01(\t\x12\x13\n\x0btotal_items\x18\x08 \x01(\x05\x12\x12\n\nsuccessful\x18\t \x01(\x05\x12\x0e\n\x06\x66\x61iled\x18\n \x01(\x05\x12\x0f\n\x07skipped\x18\x0b \x01(\x05\"\xc8\x01\n\x12ProcessForkedEvent\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x19\n\x11parent_process_id\x18\x02 \x01(\t\x12\x18\n\x10\x63hild_process_id\x18\x03 \x01(\t\x12\x0f\n\x07step_id\x18\x04 \x01(\t\x12\x14\n\x0cservice_name\x18\x05 \x01(\t\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0f\x65stimated_items\x18\x07 \x01(\x05\"\x87\x02\n\x11ProcessBatchEvent\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x12\n\nprocess_id\x18\x02 \x01(\t\x12\x19\n\x11parent_process_id\x18\x03 \x01(\t\x12\x0f\n\x07step_id\x18\x04 \x01(\t\x12\x14\n\x0cservice_name\x18\x05 \x01(\t\x12-\n\ttimestamp\x18\x06 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x17\n\x0fitems_published\x18\x07 \x01(\x05\x12\x12\n\nsuccessful\x18\x08 \x01(\x05\x12\x0e\n\x06\x66\x61iled\x18\t \x01(\x05\x12\x0f\n\x07skipped\x18\n \x01(\x05\x12\x0f\n\x07outcome\x18\x0b \x01(\tB,Z*github.com/Nvision-x/pipeline-lib-go/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'process_events_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z*github.com/Nvision-x/pipeline-lib-go/proto'
  _globals['_PROCESSSTARTEDEVENT']._serialized_start=85
  _globals['_PROCESSSTARTEDEVENT']._serialized_end=255
  _globals['_PROCESSCOMPLETEDEVENT']._serialized_start=258
  _globals['_PROCESSCOMPLETEDEVENT']._serialized_end=521
  _globals['_PROCESSFORKEDEVENT']._serialized_start=524
  _globals['_PROCESSFORKEDEVENT']._serialized_end=724
  _globals['_PROCESSBATCHEVENT']._serialized_start=727
  _globals['_PROCESSBATCHEVENT']._serialized_end=990
# @@protoc_insertion_point(module_scope)
