# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: s3_fork.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    's3_fork.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rs3_fork.proto\x12\x18pipeline.connector.s3.v1\"s\n\x06S3Fork\x12\x14\n\x0cparquet_name\x18\x01 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x02 \x01(\t\x12\x1c\n\x14\x64\x61tasource_access_id\x18\x03 \x01(\t\x12\x0e\n\x06job_id\x18\x04 \x01(\t\x12\x15\n\rdatasource_id\x18\x05 \x01(\t\"\x87\x01\n\x0cS3ForkReport\x12\x14\n\x0cparquet_name\x18\x01 \x01(\t\x12\x0e\n\x06\x62ucket\x18\x02 \x01(\t\x12\x1c\n\x14\x64\x61tasource_access_id\x18\x03 \x01(\t\x12\x0e\n\x06job_id\x18\x04 \x01(\t\x12\x15\n\rdatasource_id\x18\x05 \x01(\t\x12\x0c\n\x04root\x18\x06 \x01(\tB:Z8github.com/Nvision-x/s3-inventory-connector-go/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 's3_fork_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/Nvision-x/s3-inventory-connector-go/api/proto'
  _globals['_S3FORK']._serialized_start=43
  _globals['_S3FORK']._serialized_end=158
  _globals['_S3FORKREPORT']._serialized_start=161
  _globals['_S3FORKREPORT']._serialized_end=296
# @@protoc_insertion_point(module_scope)
