# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sharepoint_scan.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sharepoint_scan.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15sharepoint_scan.proto\x12 pipeline.connector.sharepoint.v1\"\x7f\n\x19SharepointDiscoveredDrive\x12\x1c\n\x14\x64\x61tasource_access_id\x18\x01 \x01(\t\x12\x0f\n\x07site_id\x18\x02 \x01(\t\x12\x10\n\x08\x64rive_id\x18\x03 \x01(\t\x12\x0c\n\x04path\x18\x04 \x01(\t\x12\x13\n\x0bpath_unique\x18\x05 \x01(\tB;Z9github.com/Nvision-x/sharepoint-connector-be-go/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sharepoint_scan_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/Nvision-x/sharepoint-connector-be-go/api/proto'
  _globals['_SHAREPOINTDISCOVEREDDRIVE']._serialized_start=59
  _globals['_SHAREPOINTDISCOVEREDDRIVE']._serialized_end=186
# @@protoc_insertion_point(module_scope)
