# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sharepoint_credentials.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'sharepoint_credentials.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1csharepoint_credentials.proto\x12 pipeline.connector.sharepoint.v1\"O\n\x10SharePointClient\x12\x11\n\tclient_id\x18\x01 \x01(\t\x12\x15\n\rclient_secret\x18\x02 \x01(\t\x12\x11\n\ttenant_id\x18\x03 \x01(\t\"\x86\x01\n\x14SharePointCredential\x12\x43\n\x07\x63lients\x18\x01 \x03(\x0b\x32\x32.pipeline.connector.sharepoint.v1.SharePointClient\x12\x14\n\x0cmax_inflight\x18\x02 \x01(\x05\x12\x13\n\x0bis_onedrive\x18\x03 \x01(\x08\x42;Z9github.com/Nvision-x/sharepoint-connector-be-go/api/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sharepoint_credentials_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z9github.com/Nvision-x/sharepoint-connector-be-go/api/proto'
  _globals['_SHAREPOINTCLIENT']._serialized_start=66
  _globals['_SHAREPOINTCLIENT']._serialized_end=145
  _globals['_SHAREPOINTCREDENTIAL']._serialized_start=148
  _globals['_SHAREPOINTCREDENTIAL']._serialized_end=282
# @@protoc_insertion_point(module_scope)
